version: '3.8'

services:
  myhomeapp:
    build: 
      context: .
      args:
        - BUILD_DATE=2025-07-14-v2
    ports:
      - "12344:3000"
    volumes:
      - /volume4/root4/AppData/MyHomeApp/database:/app/data
      - /volume4/root4/AppData/MyHomeApp/config:/app/config
      - /volume4/root4/AppData/MyHomeApp/logs:/app/logs
      - /volume1:/nas/volume1:ro
      - /volume2:/nas/volume2:ro
      - /volume3:/nas/volume3:ro
      - /volume4:/nas/volume4:ro
      - /volume5:/nas/volume5:ro
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
      - CONFIG_PATH=/app/config
      - LOGS_PATH=/app/logs
    restart: unless-stopped
    container_name: myhomeapp
    user: "0:0"  # Run as root to fix permission issues
