version: '3.8'

services:
  myhomeapp:
    image: myhomeapp:${BUILD_VERSION:-latest}
    build: 
      context: .
      args:
        - BUILD_DATE=2025-07-14-v4
    ports:
      - "12344:3000"
    volumes:
      - /volume4/root4/AppData/MyHomeApp/database:/app/data
      - /volume4/root4/AppData/MyHomeApp/config:/app/config
      - /volume4/root4/AppData/MyHomeApp/logs:/app/logs
      - /volume1:/nas/volume1:ro
      - /volume2:/nas/volume2:ro
      - /volume3:/nas/volume3:ro
      - /volume4:/nas/volume4:ro
      - /volume5:/nas/volume5:ro
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data
      - CONFIG_PATH=/app/config
      - LOGS_PATH=/app/logs
      - CRON_SECRET=mysecretcronjobkey # Change this in production
    restart: unless-stopped
    container_name: myhomeapp
    user: "0:0"  # Run as root to fix permission issues

  cron:
    image: alpine:latest
    depends_on:
      - myhomeapp
    command: >
      sh -c "apk add --no-cache curl && echo '0 2 * * * curl -X POST -H \"Authorization: Bearer mysecretcronjobkey\" http://myhomeapp:3000/api/anime/cron-sync' > /etc/crontabs/root && crond -f -d 8"
    restart: unless-stopped
    container_name: myhomeapp-cron
